language: elixir

elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.1

otp_release:
  - 18.3
  - 19.3
  - 20.3
  - 21.2

script: "mix local.rebar --force && mix local.hex --force && mix deps.get && mix test"
