defmodule WebAuthnLite.SignatureTest do
  use ExUnit.Case, async: false

  alias WebAuthnLite.Signature
  doctest Signature

  @b64_url_encoded_attestation_object "o2NmbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEYwRAIgCAmn7Z2OMQ5KAt4mudguloS7cE2UxCTW8G1n2syZaXoCIHO1V8Ll24v4a_pcSGq93lpZviyep1W1AUEi5GaWhKM8Y3g1Y4FZAsIwggK-MIIBpqADAgECAgR0hv3CMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMTI1l1YmljbyBVMkYgUm9vdCBDQSBTZXJpYWwgNDU3MjAwNjMxMCAXDTE0MDgwMTAwMDAwMFoYDzIwNTAwOTA0MDAwMDAwWjBvMQswCQYDVQQGEwJTRTESMBAGA1UECgwJWXViaWNvIEFCMSIwIAYDVQQLDBlBdXRoZW50aWNhdG9yIEF0dGVzdGF0aW9uMSgwJgYDVQQDDB9ZdWJpY28gVTJGIEVFIFNlcmlhbCAxOTU1MDAzODQyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElV3zrfckfTF17_2cxPMaToeOuuGBCVZhUPs4iy5fZSe_V0CapYGlDQrFLxhEXAoTVIoTU8ik5ZpwTlI7wE3r7aNsMGowIgYJKwYBBAGCxAoCBBUxLjMuNi4xLjQuMS40MTQ4Mi4xLjEwEwYLKwYBBAGC5RwCAQEEBAMCBSAwIQYLKwYBBAGC5RwBAQQEEgQQ-KAR84wKTRWABhcRH57cfTAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQAxXEiA5ppSfjhmib1p_Qqob0nrnk6FRUFVb6rQCzoAih3cAflsdvZoNhqR4jLIEKecYwdMm256RusdtdhcREifhop2Q9IqXIYuwD8D5YSL44B9es1V-OGuHuITrHOrSyDj-9UmjLB7h4AnHR9L4OXdrHNNOliXvU1zun81fqIIyZ2KTSkC5gl6AFxNyQTcChgSDgr30Az8lpoohuWxsWHz7cvGd6Z41_tTA5zNoYa-NLpTMZUjQ51_2Upw8jBiG5PEzkJo0xdNlDvGrj_JN8LeQ9a0TiEVPfhQkl-VkGIuvEbg6xjGQfD-fm8qCamykHcZ9i5hNaGQMqITwJi3KDzuaGF1dGhEYXRhWQFXSZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NBAAAACfigEfOMCk0VgAYXER-e3H0AEAzBTsfxBH3OBLagEFPu1HGkAQMDOQEAIFkBAOliDUrHsP-pW4IocnK3zBldG45XCSEm1Na2JGGEUCbqOrY-0aqcCfW33emYN6EPwYK4VPvroyC9tPyBFCrJeaL7sXO9C96n0jHbDsG1LEKMlLjOmspHGbjId0FGNcOmWICkD9UmKwqPUjdZHb6qhrGmXw6gHQvt9epBNvTeuGwYbYd4zioFH1KzJTJoXFLAeP095dmqJgqhwAR6jYxWwQaMYFlCyz1v7mfFCNiUzIh39OqRWABLDTpG-hfdxKdJkEDElVAP2RI4ZsDO3RLb4J4cnGubqX2wpdZcZKqCJvoohIarORVGmtC4gFGOBEf2tDueEho2mxoZ19nhzlfwFLshQwEAAQ"
  @b64_url_encoded_authenticator_data "SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2MBAAAACg"
  @b64_url_encoded_client_data_json "eyJjaGFsbGVuZ2UiOiJSb0F1Ym15SlJlZWJjRGYwZTdHMFdTdGxFdlp4Qm9IbXhpSkhTLTFjbS1RIiwib3JpZ2luIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIiwidHlwZSI6IndlYmF1dGhuLmdldCJ9"

  test "valid?" do
    {:ok, attestation_object} =
      @b64_url_encoded_attestation_object |> WebAuthnLite.AttestationObject.decode()

    public_key = attestation_object.auth_data.attested_credential_data.credential_public_key

    {:ok, authenticator_data} =
      @b64_url_encoded_authenticator_data |> WebAuthnLite.AuthenticatorData.decode()

    {:ok, client_data_json} =
      @b64_url_encoded_client_data_json |> WebAuthnLite.ClientDataJSON.decode()

    refute Signature.valid?("a", authenticator_data, client_data_json, public_key)
  end
end
