name: CI
on: [push, pull_request]
jobs:
  build:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['22.3.4', '23.3.4', '24.2.2']
        elixir: ['1.10.4', '1.11.4', '1.12.3', '1.13.3']
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      MIX_TEST_PARTITION: 5
    steps:
      - uses: erlef/setup-beam@v1.8
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/checkout@v2
      - run: mix local.rebar --force 
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix compile
      - run: mix test