name: CI
on: [push, pull_request]
jobs:
  build:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.3.4.7', '25.0.4', '25.1.2', '25.2', '26.0.2']
        elixir: ['1.15.2']
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      MIX_TEST_PARTITION: 5
    steps:
      - uses: erlef/setup-beam@v1.8
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/checkout@v2
      - run: mix local.rebar --force 
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix compile
      - run: mix test